# Generated by Django 5.2 on 2025-05-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VanillaBondSecMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier_client", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=100)),
                ("fixed_coupon", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "frequency",
                    models.IntegerField(
                        default=2,
                        help_text="Number of coupon payments per year (default is 2)",
                    ),
                ),
                ("maturity", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Curve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adate", models.DateField()),
                ("curve_name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("rate", models.FloatField(help_text="Swap rate in percent")),
            ],
            options={
                "ordering": ["adate", "curve_name", "year"],
                "unique_together": {("adate", "curve_name", "year")},
            },
        ),
        migrations.CreateModel(
            name="StressScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_id", models.IntegerField()),
                ("period_number", models.IntegerField()),
                ("simulation_number", models.IntegerField()),
                ("period_length", models.FloatField(help_text="Length in years")),
                (
                    "parallel_shock_size",
                    models.FloatField(help_text="Shock size in percentages"),
                ),
                (
                    "curve_snapshot",
                    models.ForeignKey(
                        help_text="Reference to curve point for given name/date/year",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed_income.curve",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("scenario_id", "period_number", "simulation_number")
                },
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=100)),
                ("position_date", models.DateField()),
                ("lot_id", models.IntegerField()),
                ("asset_name", models.CharField(max_length=100)),
                ("identifier_client", models.CharField(max_length=100)),
                (
                    "identifier_isin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "identifier_cusip",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "identifier_sedol",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "notional_amount",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("par_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("book_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("book_value", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed_income.stressscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AborPnL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=100)),
                ("identifier_client", models.CharField(max_length=100)),
                ("period_date", models.DateField()),
                ("begin_period_date", models.DateField()),
                ("end_period_date", models.DateField()),
                ("income_pnl", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "amortization_accretion_pnl",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                (
                    "realized_gain_loss_pnl",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed_income.stressscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=100)),
                ("identifier_client", models.CharField(max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("CASH_IN", "Cash In"),
                            ("CASH_OUT", "Cash Out"),
                        ],
                        max_length=10,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_price",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("lot_id", models.IntegerField()),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed_income.stressscenario",
                    ),
                ),
            ],
        ),
    ]
