# Generated by Django 5.2 on 2025-05-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_income", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="scenario",
        ),
        migrations.AddField(
            model_name="position",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="discounted_value",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="book_price",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.CreateModel(
            name="ScenarioPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=100)),
                ("position_date", models.DateField()),
                ("lot_id", models.IntegerField()),
                ("asset_name", models.CharField(max_length=100)),
                ("identifier_client", models.CharField(max_length=100)),
                (
                    "identifier_isin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "identifier_cusip",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "identifier_sedol",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "notional_amount",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("par_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("book_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("book_value", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "discounted_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fixed_income.stressscenario",
                    ),
                ),
            ],
        ),
    ]
