# Generated by Django 5.2 on 2025-05-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fixed_income",
            "0002_remove_position_scenario_position_discounted_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stressscenario",
            old_name="curve_snapshot",
            new_name="curve",
        ),
        migrations.AlterUniqueTogether(
            name="stressscenario",
            unique_together={
                ("scenario_id", "period_number", "simulation_number", "curve")
            },
        ),
    ]
